export default {
  BG_COLOR_MAIN: '#F2F3F4',
  BG_COLOR_SECOND: '#FFFFFF',

  TAB_COLOR: '#FFFFFF',
  TAB_HEIGHT: 85,

  MAIN_COLOR: '#FF8527',
  DEFAULT_COLOR: '#000000',
  DEFAULT_LIGHT_COLOR: '#FFFFFF',

  MAIN_TEXT_COLOR: '#000000',
  SECOND_TEXT_COLOR: '#636773',
  THIRD_TEXT_COLOR: '#FF8527',
  FOURTH_TEXT_COLOR: '#FFFFFF',
  MAIN_FF: 'RecoletaMedium',
  SECOND_FF: 'CeraProMedium',
  MAIN_TEXT_FS: 16,
  MAIN_TEXT_LH: 24,

  HEADER_FS_BIG: 39,
  HEADER_LH_BIG: 54,
  HEADER_FS_MEDIUM: 24,
  HEADER_LH_MEDIUM: 33,
  HEADER_FS_SMALL: 20,
  HEADER_LH_SMALL: 27,

  TITLE_FS_BIG: 24,
  TITLE_LH_BIG: 30,
  TITLE_FS_MEDIUM: 20,
  TITLE_LH_MEDIUM: 25,
  TITLE_FS_SMALL: 16,
  TITLE_LH_SMALL: 20,

  BORDER_COLOR: '#E1E2E3',
  BORDER_WIDTH: 1,
  BORDER_LOGO_WIDTH: 1.5,
  BORDER_RADIUS_BIG: 100,
  BORDER_RADIUS: 16,
  BORDER_SMALL_RADIUS: 12,
  BORDER_EXSMALL_RADIUS: 8,

  PLACEHOLDER_COLOR: '#B3B4BA',
  INPUT_BG: '#F2F3F4',
};
